--@block
CREATE TABLE User(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    UNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL 
);
--@block
INSERT INTO User (EMAIL,UNAME,PASSWORD)
VALUES('jeraponteesup@gmail.com','EarthChaotic','earth2102')

--@block
DELETE FROM User;
--@block
DELETE FROM FriendRequests;
--@block
DROP TABLE