--@block
CREATE TABLE Users(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    UNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORDS VARCHAR(255) NOT NULL UNIQUE
);
--@block